/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import controller.GestManegmentDataUser;
import java.sql.SQLDataException;
import model.DataBankAccount;
import model.DataUser;
import controller.GestManegmentDataBankAccount;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import model.DataTransaction;

/**
 *
 * @author 182120019
 */
public class usuarioTela extends javax.swing.JInternalFrame {

    /**
     * Creates new form usuarioTela
     */
    
    public usuarioTela() {
        initComponents();        
        jPanel2.setVisible(false);
        telaLogin TL = new telaLogin();
        TL.setVisible(false);
        
    }

    DefaultTableModel user = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"ID", "BALANCE", "BANK"});
    telaLogin TL1 = new telaLogin();
    int id = TL1.id;

    public void showBankAccountUser() {
        ArrayList<DataBankAccount> lista = new ArrayList<>();
        try {
            GestManegmentDataUser GMDU = new GestManegmentDataUser();
            //receber o retorno do método que está em ControleContato
            DataUser DU = new DataUser();
            DU.setIdUser(id);
            lista = GMDU.listBankingAccount(DU);
            //limpar a interface da tabela
            user.setNumRows(0);//set zero linhas
            //percorrer a tabela na interface para colocar os registros que resultou da query(SELECT)
            for (int i = 0; i < lista.size(); i++) {
                user.addRow(
                        new String[]{
                            Integer.toString(lista.get(i).getIdAccount()),
                            Float.toString(lista.get(i).getBalance()),
                            Integer.toString(lista.get(i).getBankId()),
                            Integer.toString(lista.get(i).getUserId())
                        }
                //string é uma classe, então precisa instanciar a cada nova volta
                );
            }
            tableDataContact1.setModel(user);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro na tabela.\nCausa: " + erro.getMessage(), "Erro", 0);
        }
    }

    DefaultTableModel contaBanco = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"ID", "NOME", "BANK", "EMAIL"});

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAtualizar2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataContact = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableDataContact1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnEditar3 = new javax.swing.JButton();
        btnAtualizar1 = new javax.swing.JButton();
        btnEditar4 = new javax.swing.JButton();
        btnEditar5 = new javax.swing.JButton();
        btnVC1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("VALOR");

        btnAtualizar2.setText("<html> <h2>Confirmar</h2> </html>");
        btnAtualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar2ActionPerformed(evt);
            }
        });

        tableDataContact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "ID BANK", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDataContact);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(btnAtualizar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtualizar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );

        tableDataContact1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "BALANCE", "BANK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableDataContact1);

        btnEditar3.setText("<html> <H2>Transferir</H2> </html>");
        btnEditar3.setToolTipText("");
        btnEditar3.setActionCommand("<html> <H2>Transferir</H2> </html>");
        btnEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar3ActionPerformed(evt);
            }
        });

        btnAtualizar1.setText("<html> <h2>Apagar</h2> </html>");
        btnAtualizar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizar1MouseClicked(evt);
            }
        });
        btnAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizar1ActionPerformed(evt);
            }
        });

        btnEditar4.setText("<html> <H2>Gerar historico</H2> </html>");
        btnEditar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar4ActionPerformed(evt);
            }
        });

        btnEditar5.setText("<html> <H2>Atualizar Senha</H2> </html>");
        btnEditar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditar5ActionPerformed(evt);
            }
        });

        btnVC1.setText("<html> <H2>Visualizar </H2> </html>");
        btnVC1.setToolTipText("");
        btnVC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnVC1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnAtualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnEditar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar1)
                    .addComponent(btnEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnVC1.getAccessibleContext().setAccessibleName("Visualizar");
        btnVC1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(489, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(358, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVC1ActionPerformed
        showBankAccountUser();
    }//GEN-LAST:event_btnVC1ActionPerformed

    private void btnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar3ActionPerformed
        // TODO add your handling code here:
        //TRANSFERÊNCIA
        jPanel2.setVisible(true);
    }//GEN-LAST:event_btnEditar3ActionPerformed

    private void btnAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar1ActionPerformed
        // TODO add your handling code here:
        //APAGAR
        
        
        
    }//GEN-LAST:event_btnAtualizar1ActionPerformed

    private void btnEditar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar4ActionPerformed
        // TODO add your handling code here:
        //PDF
         try{
        DataBankAccount DBA = new DataBankAccount();
        DBA.setIdAccount(id);
        GestManegmentDataBankAccount GMDBA = new GestManegmentDataBankAccount();
        GMDBA.PDFtransactions(DBA);
        }catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao imprimir PDF.\nCausa: " + erro.getMessage(), "Erro", 0);
        }
    
    }//GEN-LAST:event_btnEditar4ActionPerformed

    private void btnEditar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditar5ActionPerformed
        // TODO add your handling code here:
        //SENHA
        
               
                
                
    }//GEN-LAST:event_btnEditar5ActionPerformed

    private void btnAtualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizar2ActionPerformed
        // TODO add your handling code here:
        //CONFIRMAR VALOR DE TRANSAÇÃO
    }//GEN-LAST:event_btnAtualizar2ActionPerformed

    private void btnAtualizar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizar1MouseClicked
        // TODO add your handling code here:
        
        try {
            
            //pegar o retorno da linha selecionada na interface
            int linha = tableDataContact1.getSelectedRow();
            System.out.println(""+tableDataContact1.getSelectedRow());
            //se a linha foi selecionada
            if (linha != -1) {
                //pegar o valor através(PK) da referência de linha e coluna
                String codigo = (String) tableDataContact1.getValueAt(linha, 0);
                DataBankAccount DBA = new DataBankAccount();
                DataTransaction DT = new DataTransaction();
                //converter string para inteiro
                DBA.setIdAccount(Integer.parseInt(codigo));
                DT.setStartAccount(Integer.parseInt(codigo));
                GestManegmentDataBankAccount GMDBA = new GestManegmentDataBankAccount();
                GMDBA.deleteBankAccount(DBA, DT);

                //atualizar tabela depois de deletar
                showBankAccountUser();

                //mensagem
                JOptionPane.showMessageDialog(null, "Conta deleta.", "SUCESSO", 1);

//atualizar a tabela depois de deletar
            } else {
                throw new SQLDataException("Selecione uma linha.");
                
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Erro ao apagar conta.\nCausa: " + erro.getMessage(), "Erro", 0);
        }
    }//GEN-LAST:event_btnAtualizar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar1;
    private javax.swing.JButton btnAtualizar2;
    private javax.swing.JButton btnEditar3;
    private javax.swing.JButton btnEditar4;
    private javax.swing.JButton btnEditar5;
    private javax.swing.JButton btnVC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tableDataContact;
    private javax.swing.JTable tableDataContact1;
    // End of variables declaration//GEN-END:variables
}
